**Gerando matriz com numpy**

In [6]:
import numpy as np

In [27]:
x = np.random.rand (100, 100000) 
print("Array x:" ) 
print(x)

Array x:
[[0.95290939 0.99438538 0.86564083 ... 0.84735179 0.0262529  0.74662568]
 [0.89117452 0.53393411 0.26295133 ... 0.80394553 0.32787719 0.08929154]
 [0.01959983 0.22355006 0.53970704 ... 0.66491355 0.21941999 0.26694724]
 ...
 [0.95334978 0.99830533 0.687086   ... 0.98489691 0.77682589 0.71655169]
 [0.69622551 0.31078936 0.75314716 ... 0.65075083 0.94343684 0.33947794]
 [0.37054918 0.57367366 0.93149318 ... 0.53750298 0.29104263 0.03512582]]


In [13]:
print("\n Shape of Array x:") 


 Shape of Array x:


In [14]:
print(x.shape)

(100, 100)


In [26]:
np.random.randint(0, 2, size=100)

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0])

In [24]:
import numpy as np

# solution
rng = np.random.RandomState(42)
data, target = rng.randn(100, 100000), rng.randint(0, 2, size=100)

In [25]:
# solution
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

# solution
model = LogisticRegression()
test_score = cross_val_score(model, data, target, n_jobs=2)
print(f"The mean accuracy is: {test_score.mean():.3f}")

The mean accuracy is: 0.550


In [29]:
# solution
from sklearn.model_selection import train_test_split

# solution
data_train, data_test, target_train, target_test = train_test_split(
    data, target, random_state=0)
feature_selector.fit(data_train, target_train)
data_train_subset = feature_selector.transform(data_train)
data_test_subset = feature_selector.transform(data_test)
model.fit(data_train_subset, target_train)
test_score = model.score(data_test_subset, target_test)
print(f"The mean accuracy is: {test_score:.3f}")

NameError: name 'feature_selector' is not defined

In [30]:
# solution
from sklearn.pipeline import make_pipeline

# solution
model = make_pipeline(feature_selector, LogisticRegression())
test_score = cross_val_score(model, data, target)
print(f"The mean accuracy is: {test_score.mean():.3f}")

NameError: name 'feature_selector' is not defined