In [65]:
import numpy as np
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [66]:
# para os pesos serem selecionados aleatoriamente para garantir a reprodutibilidade dos experimentos definimos um valor aleatorio para as  seed
np.random.seed(5) # semente de aleatoriedade 

In [67]:
# carregando o dataset iris
iris = datasets.load_iris()

In [68]:
# pegando os dados e rótulos
X = iris.data
y = iris.target

In [69]:
# colocando os dados na mesma escala(normalizando)para melhorar a acurácia de teste
# definindo o objeto
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [70]:
# aleatorizando os dados do mesmo modo tanto em 'x' quanto em 'y', antes de dividir o dataset em treinaemnto e teste
# para isso deve-se criar um array de números (que serão os índices) e aleatorizar para usar tanto nos dados de treino como de teste

sufInd = np.arange(150) # gerando uma sequência de 150 números aleatórios de 0 a 149.
np.random.shuffle(sufInd) # mistura aleatoriamente e susbtitui na mesma variável(inplace).

In [71]:
# separando os dados em treino e teste
# o dataset iris tem 150 amostras assim a divisão ficou em: 
X_train = X[sufInd[:100],:] # as primeiras 100 amostras são para treinar, pegando todas as colunas
X_test = X[sufInd[100:],:] # as 50 amostras são para testar
y_train = y[sufInd[:100]]
y_test = y[sufInd[100:]] # pegando todos os índices do início ao fim

In [83]:
# criando um objeto da classe MLPClassifier 'clf = MLPClassifier'
# hidden_layer_sizes é uma tupla de números em que cada elemento diz a quantidade de neurônios você quer na camada oculta se passar o número por parâmetro quer dizer a qtd de neurônios
# learnig_rate_init é a taxa de aprendizagem da rede neural. Fator now que multiplica no ajsute dos pesos
# max_iter é a quantidade de épocas, a quantidade de vezes que no algoritmo a propagação para frente e para trás (Feedforward propagation)
# 'sgd' gradiente decrescente estocástico é o tipo de algoritmo

clf = MLPClassifier(solver='sgd', hidden_layer_sizes=(3,), learning_rate_init=0.1, activation='logistic', max_iter=1500, random_state=1)
clf.fit(X_train, y_train) #fit dos pesos com os dados que tenho de treinamento
y_pred = clf.predict_proba(X_test) #retorna as probabilidade de cada elemento ser de uma determinada classe
y_aux = np.argmax(y_pred, 1) # procura em todas as linhas qual a coluna que possui a maior probabilidade e retorna no array y_aux
y_pred # sai com 3 probabilidades dos dados serem da classe 0,1 e 2

array([[3.38724427e-03, 9.51036357e-01, 4.55763991e-02],
       [5.44036582e-03, 9.77617828e-01, 1.69418067e-02],
       [9.87985173e-01, 1.20146745e-02, 1.52074910e-07],
       [4.58375109e-03, 9.75992920e-01, 1.94233288e-02],
       [8.14635233e-04, 3.19624444e-01, 6.79560920e-01],
       [1.03467865e-02, 9.87157139e-01, 2.49607445e-03],
       [9.89072800e-01, 1.09270682e-02, 1.31690326e-07],
       [1.96910550e-03, 9.88754675e-01, 9.27621918e-03],
       [1.53755175e-04, 7.59299713e-02, 9.23916274e-01],
       [2.07152754e-05, 1.58689640e-02, 9.84110321e-01],
       [1.46201033e-05, 9.72726902e-03, 9.90258111e-01],
       [1.69669937e-05, 1.15101758e-02, 9.88472857e-01],
       [9.89376702e-01, 1.06231722e-02, 1.26156622e-07],
       [9.89501079e-01, 1.04987971e-02, 1.23748137e-07],
       [3.12097908e-04, 1.80965512e-01, 8.18722390e-01],
       [1.25615165e-05, 9.88374092e-03, 9.90103698e-01],
       [9.87728918e-01, 1.22709248e-02, 1.56802239e-07],
       [6.76341922e-04, 5.55788

In [84]:
# avaliando os dados através da métrica de acurácia 
# o resultado 0.28 é muito ruim, é necessário fazer ajustes nos parâmetros e normalizar
accuracy_score(y_test, y_aux)

0.98

In [85]:
X_train

array([[-5.25060772e-02, -8.22569778e-01,  8.07091462e-02,
         8.77547895e-04],
       [ 3.10997534e-01, -1.05276654e+00,  1.04694540e+00,
         2.64141916e-01],
       [-5.25060772e-02, -5.92373012e-01,  7.62758269e-01,
         1.58046376e+00],
       [-1.74885626e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [ 1.64384411e+00,  1.24920112e+00,  1.33113254e+00,
         1.71209594e+00],
       [-1.14301691e+00, -1.51316008e+00, -2.60315415e-01,
        -2.62386821e-01],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [ 6.86617933e-02,  3.28414053e-01,  5.92245988e-01,
         7.90670654e-01],
       [-1.02184904e+00, -1.31979479e-01, -1.22655167e+00,
        -1.31544430e+00],
       [-5.37177559e-01, -1.31979479e-01,  4.21733708e-01,
         3.95774101e-01],
       [-2.94841818e-01, -1.31979479e-01,  4.21733708e-01,
         3.95774101e-01],
       [ 5.53333275e-01, -5.92373012e-01,  7.62758269e-01,
      

In [86]:
print(y_test[:10], y_aux[:10]) # imprimindo as 10 primeiras amostras apra ver se tem erros e o que ele acertou

[1 1 0 1 2 1 0 1 2 2] [1 1 0 1 2 1 0 1 2 2]


Bibliografia : https://www.youtube.com/watch?v=UaqzXSAaqkw